### ISSUE TITLE
Terminal preset command does not open presets

### ISSUE THREAD

**Issue by hectorperdomo** [ClementVidal/terminal-presets#2]
Hello @ClementVidal,

### Very nice and much looked for extension!

I hope you can help me with this.  I am not able to get the _Terminal presets_ commandlet to open the presets.

Here is my **.terminal-presets.json** contents:

```
{
  "presets": [
    {
      "name": "My App",
      "terminals": [
        {
          "name": "Api",
          "icon": "terminal-view-icon",
          "message": "hello",
          "color": "red",
          "cwd": "./user-api",
          "env": {},
          "command": "echo yo"
        },
        {
          "name": "Application",
          "icon": "terminal-view-icon",
          "message": "hello",
          "color": "red",
          "cwd": "./user-application",
          "env": {},
          "command": "echo yo"
        }
      ]
    }
  ]
}
```
Here is the location of the config file in my workspace:

   ![image](https://user-images.githubusercontent.com/1917730/135712785-f51abc47-6f67-4845-82a8-a90fd495addb.png)

Thank you,
Hector

**Comment by ClementVidal** [comment]
Hello @hectorperdomo
Did you see any error message popping around ?

What os are you using, I did not test the extension on windows ... 

And last question, when you invoke the extension from the command palette can you see the "My app" entry or is the list empty ?

**Comment by hectorperdomo** [comment]
Thanks for responding.
